### ISSUE TITLE
Unit of the element of Heisenberg interaction matrix

### ISSUE THREAD

**Issue by yw-fang** [fbuessen/SpinMC.jl#11]
Hi, @fbuessen  thank you for your code written in Julia. I didn't notice this code until yesterday. It's strange to me, because in all the samples, the exchange interaction matrix is always like this: M = [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0], I'm wondering what's the unit of the element 1? Or in SpinMC.jl, it has to be normalized? 

In addition, in the example https://github.com/fbuessen/SpinMC.jl#specific-heat-and-magnetization-of-a-cubic-lattice-heisenberg-ferromagnet how to consider the influence of magnetic moment on the simulation of Curie temperature? Thanks very much!

**Comment by fbuessen** [comment]
Hi @yw-fang, the spin Hamiltonian that is simulated by the code is defined as 
$H=\sum_{i,j} \mathbf{S}_i \cdot \mathbf{M} _{ij}  \cdot \mathbf{S}_j + \sum_i \mathbf{S}_i \cdot \mathbf{B}_i$ 
where the $\mathbf{S}_i$ are unit vectors. 
Therefore, any units and/or prefactors of your model will need to be absorbed in the interaction matrix. 
(In the examples the interaction constants are set to `1.0` just for simplicity.)

To study the model in the presence of a magnetic field (i.e., $\mathbf{B}_i$ non-zero), you need to specify the magnetic field strength in the definition of your lattice unit cell. 
This is briefly mentioned [here](https://github.com/fbuessen/SpinMC.jl#define-a-lattice-spin-model) and done via the function
```julia
setField!(uc, b1, [1.0, 1.0, 1.0]) # Optionally apply a magnetic field B=(1,1,1) to basis site b1. 
```
I hope this answers all your questions!

**Comment by yw-fang** [comment]
Hi @fbuessen thanks very much for your quick response. Just for an example, assuming I have two cases in which the magnetic moment in the first case is 3 $\mu_B$ and the other 4 $\mu_B$ . Both of the magnetic moments are oriented along (001). I'm wondering how to set up the 'setField'? Should the unit of magnetic field also be adsorbed in B<sub>i</sub> as the interaction matrix M<sub>ij</sub>? Thanks a lot!

**Comment by fbuessen** [comment]
Yes, the unit should be absorbed in your definition of the magnetic field $B_i$. 
For example, assume your physical Hamiltonian were $H_\mathrm{phys}=-5\mathrm{meV}\sum_{i,j} \vec{S}_i \cdot \vec{S}j - \sum_i (0,0,B)^t \cdot 3\vec{\mu}_B$ (with units of the magnetic field in T, such that your overall Hamiltonian is in units of energy, meV). 

We can write this in a form that is closer to what is simulated in code (see my previous reply), yielding $H_\mathrm{phys}/\mathrm{meV}=\sum_{i,j} \mathbf{S}_i \cdot \mathbf{M} _{ij}  \cdot \mathbf{S}_j + \sum_i \mathbf{S}_i \cdot \mathbf{B}_i$ with
$\mathbf{M} = \left(\matrix{-5 & 0 & 0 \cr 0 & -5 & 0 \cr 0 & 0 & -5} \right)$
and
$\mathbf{B}_i = \left(\matrix{0 \cr 0 \cr -3 B \mu_B / \mathrm{meV} \ } \right)$. 
Both $\mathrm{M}$ and $\mathrm{B}_i$ are now dimensionless numbers that you can feed into your model definition via `addInteraction!()` and `setField!()`. 

Note that whereas $H_\mathrm{phys}$ is in units of meV, any Hamiltonian $H$ or temperature $T$ that you feed into the SpinMC.jl code is assumed to be dimensionless, i.e. Boltzmann weights are computed as $e^{-H/T}$. 
Alternatively, you can think of it as both the Hamiltonian and the temperature having units of energy (e.g. units of meV). After running a simulation you would need to re-introduce physical units when interpreting the result. 
In physical units, the Boltzmann weight would be $e^{-H_\mathrm{phys}/(k_B T)}$ and any temperature that you extract from the simulation (e.g. Curie temperature) would therefore need to be rescaled back to physical units through division by the boltzmann factor $k_B$.

**Comment by yw-fang** [comment]
@fbuessen Get it! Thanks very much for the helpful instructions!
