### ISSUE TITLE
Coordinates for the spins

### ISSUE THREAD

**Issue by DavidRamosSal** [fbuessen/SpinMC.jl#5]
I want to plot the last state of a simulation and while the spin values can be accessed using `m.lattice.spins` I can't find a way to get their position in x,y coordinates. Is it possible to get these coordinates?

**Comment by fbuessen** [comment]
For convenient access to the spin and lattice site information, you can use the functions `getSpin(lattice, site)` and `getSitePosition(lattice, site)`, where `site=1,...,length(lattice)` and `lattice=m.lattice` in your example. 

In your example, which seems to be a 2D lattice, `getSpin` would return a tuple of the three spin components at the specified lattice site and `getSitePosition` returns a tuple of x,y coordinates of that lattice site.

**Comment by DavidRamosSal** [comment]
Thank you for your answer!
