### ISSUE TITLE
Historic values of the observables

### ISSUE THREAD

**Issue by DavidRamosSal** [fbuessen/SpinMC.jl#6]
Is it possible to recover the values of the observables at the end of each sweep? I see they're saved as LogBinners and I wonder if I can recover the original values. Thanks in advance.

**Comment by fbuessen** [comment]
Hi, unfortunately the LogBinner class doesn't store the entire time series of measurements. 
If you're interested in preserving every measurement, you can replace the `LogBinner` class with `FullBinner` (also from the BinningAnalysis package, see https://github.com/carstenbauer/BinningAnalysis.jl). 
The `FullBinner` class stores every measurement in an array-like format.

**Comment by DavidRamosSal** [comment]
Oh that's easy enough. Thanks again!

**Comment by DavidRamosSal** [comment]
Sorry to keep bothering but something breaks when making that change (changing every definition from LogBinner to FullBinner in Observables.jl).  This is the error I get when I try to import the modified package.

> ERROR: LoadError: TypeError: in Type, in A, expected A<:AbstractVector{Float64}, got a value of type Int64
Stacktrace:
  [1] top-level scope
    @ ~/.julia/packages/SpinMC/hMGuL/src/Observables.jl:3
  [2] include(mod::Module, _path::String)
    @ Base ./Base.jl:418
  [3] include(x::String)
    @ SpinMC ~/.julia/packages/SpinMC/hMGuL/src/SpinMC.jl:1
  [4] top-level scope
    @ ~/.julia/packages/SpinMC/hMGuL/src/SpinMC.jl:9
  [5] include
    @ ./Base.jl:418 [inlined]
  [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1318
  [7] top-level scope
    @ none:1
  [8] eval
    @ ./boot.jl:373 [inlined]
  [9] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [10] top-level scope
    @ none:1
in expression starting at /home/dave/.julia/packages/SpinMC/hMGuL/src/Observables.jl:3
in expression starting at /home/dave/.julia/packages/SpinMC/hMGuL/src/SpinMC.jl:1
ERROR: LoadError: Failed to precompile SpinMC [341a0f32-da10-4b75-900e-7f27269b54d1] to /home/dave/.julia/compiled/v1.7/SpinMC/jl_ULbQyS.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997
in expression starting at /home/user/Documents/try.jl:1

**Comment by fbuessen** [comment]
The `FullBinner` struct has slightly different type parameters, so you would need to make the following adjustments in Observables.jl: 
```julia
mutable struct Observables
    energy::ErrorPropagator{Float64,32}
    magnetization::FullBinner{Float64,Vector{Float64}}
    magnetizationVector::FullBinner{Vector{Float64},Vector{Vector{Float64}}}
    correlation::FullBinner{Vector{Float64},Vector{Vector{Float64}}}
end

function Observables(lattice::T) where T<:Lattice
    return Observables(ErrorPropagator(Float64), FullBinner(Float64), FullBinner(Vector{Float64}), FullBinner(Vector{Float64})) 
end
```

You can then access the full time series of measurements e.g. in `Observables.magnetization.x`.

**Comment by DavidRamosSal** [comment]
Thank you, that worked!
